version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    network_mode: host
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  server:
    image: "se.ifmo.ru/washing-server:latest"
    network_mode: host
    depends_on:
      - mosquitto
